version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

  server:
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: postgres-dev
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
    environment:
      DATABASE_URL: postgres://postgres:mysecretpassword@db:5432/postgres